spring.application.name=Tecnologia

# Configuración del servidor
server.port=${PORT:8080}
server.address=0.0.0.0


# Configuración de la Base de Datos PostgreSQL  en Render urñ externa
spring.datasource.url=jdbc:postgresql://dpg-cvgr59qj1k6c738p6lt0-a.oregon-postgres.render.com:5432/support_ge19
spring.datasource.username=user
spring.datasource.password=G2LYxb1g5HZtvrWG1ZoMAUR1GbQpWjsA
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.maximum-pool-size=3
#spring.datasource.hikari.minimum-idle=1
#spring.datasource.hikari.idle-timeout=10000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.max-lifetime=2000000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=2000000

#spring.datasource.url=${DATABASE_URL}
#spring.datasource.username=${DATABASE_USER}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de HikariCP (opcional para mejor rendimiento)


# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración del log (opcional)
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher



