spring.application.name=Tecnologia


server.port=${PORT:8080}
server.address=0.0.0.0



spring.datasource.url=jdbc:postgresql://dpg-cvgr59qj1k6c738p6lt0-a.oregon-postgres.render.com:5432/support_ge19?sslmode=require
spring.datasource.username=user
spring.datasource.password=G2LYxb1g5HZtvrWG1ZoMAUR1GbQpWjsA
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.max-lifetime=2000000


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true  
spring.jpa.properties.hibernate.format_sql=true 


logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG


springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant_path_matcher



